name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t makarovvv/gateway -f ./Dockerfile .
          docker run makarovvv/gateway npm run test:e2e

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: k8sdeploy-393913

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: k8s
          location: us-central1

      - name: Build
        run: |-
          docker build -t makarovvv/gateway:latest -t makarovvv/gateway:${{ env.SHA }} -f ./Dockerfile .

      - name: Push
        run: |-
          docker push makarovvv/gateway:latest

          docker push makarovvv/gateway:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl set image deployments/gateway-deployment gateway=makarovvv/gateway:${{ env.SHA }}
          kubectl apply -f deployments

